[features]
seeds = false
skip-lint = false
[programs.devnet]
mint_nft = "7vpEoUp3iFetyiUP7oECoBzG72ivV7LYkKum11PbV759"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/m1/.config/solana/id.json"

[scripts]
test-mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-mint.ts"
test-sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-sell.ts"
